apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zwyg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-zwyg@sha256:dd0da7fe3cef848e5029f059bf082cc28f868f78a49d530d0b4fbce2b626e516
        name: my-nodejs
        resources: {}
status: {}
